### ISSUE TITLE
Recursively delete child modules

### ISSUE THREAD

**Issue by kellyselden** [sindresorhus/clear-module#10]
I have a case where the entry point of a module was not the file storing the state, it only surfaces it. This caused me to recurse `module.children` and delete, which solved the problem. Would you like me to add this feature, perhaps behind an option?

**Comment by omrilotan** [comment]
Addressed here https://github.com/sindresorhus/clear-module/pull/9

**Comment by kellyselden** [comment]
Oppologies I missed that.
