### ISSUE TITLE
Endless recursion on circular dependencies

### ISSUE THREAD

**Issue by vectronic** [sindresorhus/clear-module#13]
Hello,

I have an issue when using clear-module within a Mocha unit test: I get an endless recursion. However if I run it outside of a test I don't.

I have successfully used clear-module in tests before. It looks to be related to:

* upgrading to clear-module: "4.1.0" as the example below works with "3.1.0"
* clearing sshpk as this has circular dependencies defined

This works fine:

```
// demo.js
require('sshpk');
const clearModule = require('clear-module');
console.log('before');
clearModule('sshpk');
console.log('after');
```

produces:

```
% node demo.js
before
after
```

However if I run using mocha, it hangs on the call to clearModule:

```
require('sshpk');
const clearModule = require('clear-module');
console.log('before');
clearModule('sshpk');
console.log('after');

describe('yyy', () => {

    it('xxx', function () {
    });
});
```

produces:

```
% ./node_modules/.bin/mocha test/services/demo.spec.js
before
```

When I debug this I can see an endless recursion of clearing the sshpk modules which have a circular reference.

I am using node 12.6.0 and the following lib versions:

* "mocha": "7.1.0"
* "clear-module": "4.1.0" (previously 3.1.0 which worked)
* "sshpk": "1.16.1"

**Comment by vectronic** [comment]
UPDATE: If I use clear-module v3.2.0 it works, but with v4.0.0 it hangs.

**Comment by sindresorhus** [comment]
Probably related to https://github.com/sindresorhus/clear-module/commit/ccd516c6f2016fc8f44c1752b873e10e51f1e1e4. You might want the `clearModule.single()` method.

// @omrilotan

**Comment by omrilotan** [comment]
I will issue a pull request this evening

**Comment by omrilotan** [comment]
I have reproduced the issue with the following steps:

- create a new npm project and install `mocha`, `sshpk`, `clear-module`

- Create a test file
```js
const sshpk = require('sshpk');
const clear = require('clear-module');

describe('reproduce this issue', () => {
	it('Should not get stuck between Before and After', () => {
		console.log('Before');
		clear('sshpk');
		console.log('After');
	})
});
```

- Run tests, get stuck after 'Before'.
- Link the solution in #14 
- Run the tests with desired result

#14 should definitely resolve this issue

**Comment by vectronic** [comment]
Confirmed fixed for me - thanks!
