### ISSUE TITLE
(node:1550) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by tosbaha** [sindresorhus/clear-module#3]
I am trying to remove the cache for mocha test. When I run the below code I get the error 

> (node:1550) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

```javascript
const glob = require('glob-promise');
const clearModule = require('clear-module');

const specs = await glob('./testfiles/*.js', { absolute: true });
console.log(specs);
specs.map(spec => {
  clearModule(spec);
  mocha.addFile(spec);
});
```

I checked more to find the error and found out that when I use following code  
```javascript
console.log(callerPath());
````
 I get null. So it seems `callerPath` can't get the folder. I tested above code with NodeJS v10.4.1

**Comment by thetutlage** [comment]
Ditto, I have the same issue with Node 10.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/clear-module/releases/tag/v3.1.0 should fix this. Let me know if it does not.
