### ISSUE TITLE
Having some troubles making clear-module working

### ISSUE THREAD

**Issue by giggioz** [sindresorhus/clear-module#5]
Hi, i'm having some problems trying to make this module running on my code (i'm quite sure i didn't fully get the whole cache concept)

Maybe it is a stackoverflow question, in that case feel free to tell me :)

Here i prepared a small repo as example

`git clone git@bitbucket.org:giggioz/test-clear-module.git`

install the modules with
`npm i `
and then run it with 
`node index.js`

This code prints every 500ms a value.
This value comes from a delegate.
Now if i change *while the code is running* the value returned by get-points.js it does not do anything... i would expect a change, right?

Thanks for your considerations!

**Comment by giggioz** [comment]
I've found [this alternative](https://stackoverflow.com/a/14801711/3438453), i think your module does not traverse correctly the dependancy tree.

Cheers!

**Comment by MCArth** [comment]
I'm also having problems with this module not correctly traversing the dependency tree. 

For anyone else running into this, I've replaced this module with https://www.npmjs.com/package/decache which works as expected (and has a very similar api so can be swapped out cleanly)
